development:
  adapter: postgresql
  encoding: unicode
  database: designation_dev
  pool: 5
  timeout: 5000
  username: Will

test:
  adapter: postgresql
  encoding: unicode
  database: designation_test
  pool: 5
  timeout: 5000
  username: Will

production:
  adapter: postgresql
  encoding: unicode
  database: designation_prod
  pool: 5
  timeout: 5000
  username: Will

stage:
  adapter: postgresql
  encoding: unicode
  database: designation_stage
  pool: 5
  timeout: 5000
  username: Will